<CONNECTOR_TO>     ::= "-->"
<CONNECTOR_FROM>   ::= "<--"
<CONNECTOR_BI>     ::= "<-->"
<TERM>             ::= "actor" | "database" | "service" | "ui" | "component"
<VERT_DELIM>       ::= ":"
<VERTEX>           ::= <TERM>"["{<ALPHA>}"]"<VERT_DELIM>
<EDGE>             ::= <CONNECTOR_TO> | <CONNECTOR_BI> | <CONNECTOR_FROM>
<ALPHA>            ::= [A-z]
<NUMBER>           ::= <RULE_NON_ZERO> | <RULE_DIGIT>
<RULE_NON_ZERO>    ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<RULE_DIGIT>       ::= "0" | <RULE_NON_ZERO>
<RULE_WHITESPACE>  ::= <RULE_WS> | ""

